### ISSUE TITLE
Use encodeUri when building the base url

### ISSUE THREAD

**Issue by philpott** [precariostecnicos/AudienceStudio#1]
https://github.com/precariostecnicos/AudienceStudio/blob/9d6ad3d64d96dbeb4f5976fe061b7222f01f8aa4/template.tpl#L386

It's a best practice to encode user provide values when building url's. In this case since your building the url path this should be done by calling out to [encodeUri](https://developers.google.com/tag-manager/templates/api#encodeuri).

Thanks
Michael

**Comment by luratic-devs** [comment]
Thanks for the feedback, @philpott . This should be now fixed by commit 5416b889f07febd00c10caf6f6ba38fd2ff2e837
