### ISSUE TITLE
Detalle en el nombre del Autor

### ISSUE THREAD

**Issue by isantolin** [precariostecnicos/AudienceStudio#2]
Hola mis Precarios:
Las tags de ustedes son las mejores que existen en el Marketplace de Google Tag Manager, pero hay un pequeño gran problema en las implementaciones, y es que a los clientes no les gusta el nombre de "precariostecnicos" que aparece en el Autor :(
Hay alguna forma de solucionar esa cuestion?

<3 Saludos y mucho amor para ustedes

**Comment by luratic-devs** [comment]
Muchas gracias por el comentario @isantolin. 

¿Tienes alguna sugerencia de nombre mejor y que esté desponible en .com? Te prometemos que si nos gusta lo cambiamos. 

Y tenemos aún más plantillas pendientes 💪 

Muchas gracias.

**Comment by luratic-devs** [comment]
Hola, 
Hemos actualizado el nombre, lo que pasa es que en las plantillas que ya teníamos aún no ha surgido efecto. 
Nuestro nuevo nombre es Luratic.
Muchas gracias.
